### ISSUE TITLE
Warning | setGeometry: Unable to set geometry

### ISSUE THREAD

**Issue by Amphaal** [Amphaal/rpgrpz#11]
Related to QGLWidget as a viewport, meant to "optimise" overall QGraphicsItems rendering (which is already bad). QOpenGLWidget is not really a QGLWidget replacement in that usecase (blackscreen rendering). Considering classic Qt UI rendering as quasi-obsolete, nothing is to be expected here in the next Qt patches. 

We need another rendering system.

**Comment by gg-vara** [comment]
Issue disapeared once Qt updated to 5.14.
