### ISSUE TITLE
[Windows] Use Sentry + Crashpad for bug reports 

### ISSUE THREAD

**Issue by Amphaal** [Amphaal/rpgrpz#13]
Mostly functionnal, lacks Github Integration on server side (https://github.com/getsentry/onpremise/issues/385), and maybe a fix for mistranslated MinGW stack traces.

**Comment by gg-vara** [comment]
Removed from alpha stage for now, will be reintegrated in beta.

**Comment by gg-vara** [comment]
Integrated as it. I'll have a look at bug report once getting some, and judging if debug infos are enough, thus maybe reopening this ticket.
