### ISSUE TITLE
[Windows 10 / Windows Defender] Behavior:Win32/executionJT!ml from , quarantined executable

### ISSUE THREAD

**Issue by Amphaal** [Amphaal/rpgrpz#25]
Reported by a user that a random Windows Defender scan found out RPGRPZ.exe as suspicious and put it in quarantine WITHOUT telling the user. May be mostly caused by the absence of application signing.

**Comment by Syler57** [comment]
![image](https://user-images.githubusercontent.com/62910686/79618562-a8cec280-810a-11ea-9625-0519d18a4adc.png)

**Comment by gg-vara** [comment]
![image](https://user-images.githubusercontent.com/13903151/99008642-d667d700-2546-11eb-9358-0b13460396cf.png)
https://www.microsoft.com/en-us/wdsi/submission/36e81eca-4319-4957-a2c3-ab0c225322e6 Should be fixed !
