### ISSUE TITLE
Too heavy (26 mo) assets aren't uploaded (players are stuck without downloading it)

### ISSUE THREAD

**Issue by Pierraurelien** [Amphaal/rpgrpz#32]

**Comment by gg-vara** [comment]
If alpha blending / transparency handling is not required, prefer using .JPEG/.JPG formats over .PNG, they are always lighter. I'll try to come up with a fix really soon ;)

**Comment by gg-vara** [comment]
Kinda fixed in #34. I'm working on a extended network audit system for hosts to tracks uploads to clients. Once this implemented, i'll close this ticket ;)

**Comment by gg-vara** [comment]
#39 added audit ;)
