### ISSUE TITLE
External IP and uPnP not shown ("uPnP : no")

### ISSUE THREAD

**Issue by Pierraurelien** [Amphaal/rpgrpz#33]

**Comment by gg-vara** [comment]
If you have trouble with uPnP, make sure that :
- Your ISP router / box need to handle this specific protocol (most do)
- Your firewall allows rpgrpz to use the network

Sometime you can get a "uPnP : no" once in a while if the app is not shutdown properly. Just restarting the app normaly fixes this issue. I plan to have a look at this and maybe fix this.
Sometimes it's just your router that fails, a reboot might fix it.
