### ISSUE TITLE
Recherche d'IP Externe charge indéfiniment

### ISSUE THREAD

**Issue by LeComteDeGuiche** [Amphaal/rpgrpz#4]
Le champ " IP Externe <Recherche>" dans la barre de statut affiche une icône de chargement indéfiniment.
![RPGRPZ_screen](https://user-images.githubusercontent.com/62909912/77960227-38d1d700-72d8-11ea-825c-86220a35650c.png)
![RPGRPZ_screen2](https://user-images.githubusercontent.com/62909912/77960237-3c655e00-72d8-11ea-85c0-4afab5e457fc.png)

**Comment by gg-vara** [comment]
As UPnP is used to get the external IP of your network and if it fails, you should not be able to host a game. Therefore "Searching.." should be updated to something like "Error" :) 

https://github.com/Amphaal/rpgrpz/commit/d90df4e92e37dd695ecce76df8507271c6197665 fixes this, TBE in the next release ;)
