### ISSUE TITLE
v.1.0.2. -> Additional unwanted straight lines when quickdrawing (only in player view)

### ISSUE THREAD

**Issue by Pierraurelien** [Amphaal/rpgrpz#41]
See https://www.youtube.com/watch?v=YH8SBEOiQsQ&feature=youtu.be&t=5071 for example

**Comment by Pierraurelien** [comment]
Quickdrawing does not appear the same way as a player or as DM : as a DM when you draw a line only the line appears, but the players can see additionnal unwanted straight lines coming from the star of the drawing and going to the end of the drawing

Translation : Quand un DM dessine un zigouigoui en quickdraw, il ne voit que son zigouigoui sur son écran. Chez les joueurs, le sus-cité zigouigoui est parasité par des lignes droites qui viennent de l'endroit où commence le dessin et qui relient directement la fin du dessin.

**Comment by gg-vara** [comment]
Zboudiboui, TBE 1.0.4
