### ISSUE TITLE
Launching the app after an update shows logo and shutdown

### ISSUE THREAD

**Issue by Syler57** [Amphaal/rpgrpz#5]
Upgrade RPGRPZ with a new version and the same path of installation create a problem.
The application won't start anymore, instead we have just the logo and ... nothing else.

The question is why does it do that ?

Version number : 0.21.0

**Comment by gg-vara** [comment]
It might be related to the cache system of the ."dll finder" of GStreamer. Once the cache system identifies an emplacement for the DLLs, it sticks with it for some reasons and do not update itself if a newer installation changes dll names and/or locations (as we just updated from plain MSVC compiled binaries to MinGW ones). Uninstalling/Reinstalling at another location resets the cache and then allows you to reinstall it at the initial, standard location.
