### ISSUE TITLE
[1.0.14] Bug report

### ISSUE THREAD

**Issue by Amphaal** [Amphaal/rpgrpz#50]
- [ ] As a client joining a game, upload indicator is always red
- [x] As a client, Host binding a player token does not allow a player to move it
- [ ] As host, connecting with empty IP field have strange behavior
- [ ] Player token inherits latest PNJ token color
- [x] a dice throw did not produce an output (only happened once)
- [ ] NPC token color change from host, not seen from clients when done 2-3 times

2 crashs : while selecting multiple atom / NPC / PC

**Comment by gg-vara** [comment]
No complaints since from users, i'd create another report if any of those issues resurface.
